version: "3.5"
services:
  docker-svelte:
    build: 
      context: ./build
      #dockerfile: Dockerfile
      target: debug
    image: svelte-docker:1.0.0
    volumes: 
      - ./build/public:/app/public
      - ./build/src:/app/src
    ports:
      #- "5050:80"
      - "5050:5000"
    #command: npm run start